spring.application.name=musicplayer
spring.datasource.url=jdbc:mysql://localhost:3306/musicapp
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.username=Music409_CloudBot
telegram.bot.token=8061375121:AAEHxqFOLMHeRoi-sk9K85b42ZuYZVsW8m8
server.url=http://localhost:8080


